import fs from 'node:fs/promises';
// No remote scripts or runtime dependencies. Bundle our own three modules for
// Chrome's classic content-script entry point.
const files=['core.js','rendered.js','reader-bridge.js'];
const source=await Promise.all(files.map(f=>fs.readFile(new URL(`../extension/${f}`,import.meta.url),'utf8')));
const bundle=source.map(s=>s.replace(/^import .*;\r?\n/gm,'').replace(/^export /gm,'')).join('\n');
await fs.writeFile(new URL('../extension/reader-content.js',import.meta.url),`// Generated by npm run build. Do not edit directly.\n(()=>{\n${bundle}\n})();\n`);
